-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action text NOT NULL,
  table_name text,
  record_id uuid,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.barangays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  city_barangay_id uuid,
  name text NOT NULL,
  pcode text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  activated_at timestamp with time zone NOT NULL DEFAULT now(),
  deactivated_at timestamp with time zone,
  last_change_reason text NOT NULL DEFAULT 'Initial seed import'::text,
  last_changed_by uuid,
  updated_at timestamp with time zone,
  CONSTRAINT barangays_pkey PRIMARY KEY (id),
  CONSTRAINT barangays_city_barangay_id_fkey FOREIGN KEY (city_barangay_id) REFERENCES public.city_barangays(id),
  CONSTRAINT barangays_last_changed_by_fkey FOREIGN KEY (last_changed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.city_barangay_geometry_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  city_barangay_id uuid NOT NULL,
  version_no integer NOT NULL,
  geometry USER-DEFINED NOT NULL,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  change_type text NOT NULL CHECK (change_type = ANY (ARRAY['create'::text, 'overwrite'::text, 'manual_edit'::text])),
  reason text NOT NULL,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT city_barangay_geometry_versions_pkey PRIMARY KEY (id),
  CONSTRAINT city_barangay_geometry_versions_city_barangay_id_fkey FOREIGN KEY (city_barangay_id) REFERENCES public.city_barangays(id),
  CONSTRAINT city_barangay_geometry_versions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.city_barangay_import_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  feature_index integer NOT NULL,
  pcode text,
  name text,
  action text NOT NULL DEFAULT 'invalid'::text CHECK (action = ANY (ARRAY['create'::text, 'skip'::text, 'overwrite'::text, 'invalid'::text, 'review_required'::text])),
  validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  normalized_geometry USER-DEFINED,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  selected_overwrite boolean NOT NULL DEFAULT false,
  existing_city_barangay_id uuid,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT city_barangay_import_items_pkey PRIMARY KEY (id),
  CONSTRAINT city_barangay_import_items_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.city_barangay_import_jobs(id),
  CONSTRAINT city_barangay_import_items_existing_city_barangay_id_fkey FOREIGN KEY (existing_city_barangay_id) REFERENCES public.city_barangays(id)
);
CREATE TABLE public.city_barangay_import_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  uploaded_by uuid NOT NULL,
  filename text NOT NULL,
  status text NOT NULL DEFAULT 'uploaded'::text CHECK (status = ANY (ARRAY['uploaded'::text, 'validated'::text, 'committed'::text, 'failed'::text, 'cancelled'::text])),
  total_features integer NOT NULL DEFAULT 0,
  valid_features integer NOT NULL DEFAULT 0,
  error_features integer NOT NULL DEFAULT 0,
  duplicate_features integer NOT NULL DEFAULT 0,
  payload_size_bytes integer,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  validated_at timestamp with time zone,
  committed_at timestamp with time zone,
  CONSTRAINT city_barangay_import_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT city_barangay_import_jobs_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.city_barangays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  pcode text NOT NULL UNIQUE,
  city text NOT NULL DEFAULT 'Dasmariñas'::text,
  geometry USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  source_fid integer,
  source_date date,
  source_valid_on date,
  source_valid_to date,
  source_area_sqkm numeric,
  updated_at timestamp with time zone,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT city_barangays_pkey PRIMARY KEY (id),
  CONSTRAINT city_barangays_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT city_barangays_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.health_station_coverage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  health_station_id uuid NOT NULL,
  barangay_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT health_station_coverage_pkey PRIMARY KEY (id),
  CONSTRAINT health_station_coverage_health_station_id_fkey FOREIGN KEY (health_station_id) REFERENCES public.health_stations(id),
  CONSTRAINT health_station_coverage_barangay_id_fkey FOREIGN KEY (barangay_id) REFERENCES public.barangays(id),
  CONSTRAINT health_station_coverage_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT health_station_coverage_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.health_stations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay_id uuid,
  name text NOT NULL,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  physical_city_barangay_id uuid NOT NULL,
  facility_type text NOT NULL DEFAULT 'BHS'::text CHECK (facility_type = ANY (ARRAY['BHS'::text, 'BHC'::text, 'HEALTH_CENTER'::text, 'OTHER'::text])),
  is_active boolean NOT NULL DEFAULT true,
  deactivated_at timestamp with time zone,
  notes text,
  updated_at timestamp with time zone,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT health_stations_pkey PRIMARY KEY (id),
  CONSTRAINT health_stations_barangay_id_fkey FOREIGN KEY (barangay_id) REFERENCES public.barangays(id),
  CONSTRAINT health_stations_physical_city_barangay_id_fkey FOREIGN KEY (physical_city_barangay_id) REFERENCES public.city_barangays(id),
  CONSTRAINT health_stations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT health_stations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  date_of_birth date NOT NULL,
  sex text CHECK (sex = ANY (ARRAY['M'::text, 'F'::text])),
  mobile_number text CHECK (mobile_number IS NULL OR mobile_number ~ '^\+639\d{9}$'::text),
  role text NOT NULL CHECK (role = ANY (ARRAY['system_admin'::text, 'city_health_officer'::text, 'phis_coordinator'::text, 'dso'::text, 'nurse_phn'::text, 'midwife_rhm'::text, 'bhw'::text])),
  health_station_id uuid,
  purok_assignment text,
  is_active boolean DEFAULT true,
  must_change_password boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  user_id text CHECK (user_id ~ '^USR-\d{4}-\d{4,}$'::text),
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  name_suffix text,
  email text NOT NULL,
  alternate_mobile_number text CHECK (alternate_mobile_number IS NULL OR alternate_mobile_number ~ '^\+639\d{9}$'::text),
  coverage_notes text,
  admin_notes text,
  last_login_at timestamp with time zone,
  password_changed_at timestamp with time zone,
  deactivation_reason text,
  profile_photo_path text,
  profile_photo_updated_at timestamp with time zone,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_health_station_id_fkey FOREIGN KEY (health_station_id) REFERENCES public.health_stations(id),
  CONSTRAINT user_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT user_profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);