import type { Patient, Encounter } from '@/types/patients'

export const mockPatients: Patient[] = [
  {
    id: 'KLD-2026-0001',
    philhealth_id: '01-050012345-6',
    last_name: 'Santos',
    first_name: 'Maria',
    middle_name: 'Cruz',
    suffix: null,
    sex: 'Female',
    date_of_birth: '1985-03-10',
    civil_status: 'Married',
    barangay: 'Salawag',
    purok: 'Purok 3',
    street_house_no: '42 Sampaguita St.',
    is_nhts: true,
    is_4ps: true,
    is_ip: false,
    created_at: '2026-01-15T08:30:00Z',
  },
  {
    id: 'KLD-2026-0002',
    philhealth_id: null,
    last_name: 'Reyes',
    first_name: 'Juan',
    middle_name: 'Bautista',
    suffix: 'Jr.',
    sex: 'Male',
    date_of_birth: '1978-11-22',
    civil_status: 'Married',
    barangay: 'Salawag',
    purok: 'Purok 1',
    street_house_no: '15 Rizal Ave.',
    is_nhts: false,
    is_4ps: false,
    is_ip: false,
    created_at: '2026-01-20T10:15:00Z',
  },
  {
    id: 'KLD-2026-0003',
    philhealth_id: '01-050098765-4',
    last_name: 'Dela Cruz',
    first_name: 'Ana',
    middle_name: null,
    suffix: null,
    sex: 'Female',
    date_of_birth: '1992-07-05',
    civil_status: 'Single',
    barangay: 'Salitran IV',
    purok: 'Purok 5',
    street_house_no: '8 Mabini St.',
    is_nhts: true,
    is_4ps: false,
    is_ip: false,
    created_at: '2026-02-01T09:00:00Z',
  },
  {
    id: 'KLD-2026-0004',
    philhealth_id: '01-050054321-0',
    last_name: 'Garcia',
    first_name: 'Pedro',
    middle_name: 'Lim',
    suffix: null,
    sex: 'Male',
    date_of_birth: '1960-01-30',
    civil_status: 'Widow/er',
    barangay: 'Salawag',
    purok: 'Purok 3',
    street_house_no: '7 Bonifacio Rd.',
    is_nhts: false,
    is_4ps: false,
    is_ip: true,
    created_at: '2026-02-10T14:20:00Z',
  },
  {
    id: 'KLD-2026-0005',
    philhealth_id: null,
    last_name: 'Villanueva',
    first_name: 'Rosa',
    middle_name: 'Mendoza',
    suffix: null,
    sex: 'Female',
    date_of_birth: '2000-09-18',
    civil_status: 'Single',
    barangay: 'Salitran IV',
    purok: 'Purok 2',
    street_house_no: '23 Aguinaldo St.',
    is_nhts: true,
    is_4ps: true,
    is_ip: false,
    created_at: '2026-03-01T07:45:00Z',
  },
]

export const mockEncounters: Encounter[] = [
  {
    id: 'ENC-0001',
    patient_id: 'KLD-2026-0001',
    consultation_type: 'New Consultation',
    weight: 58,
    height: 155,
    bp_systolic: 120,
    bp_diastolic: 80,
    temperature: 36.5,
    bmi: 24.1,
    program_category: 'Maternal',
    chief_complaint: 'Prenatal check-up, 28 weeks AOG',
    clinical_notes: 'Fundic height 26 cm. FHT 140 bpm. No edema.',
    diagnosis: 'Normal pregnancy, G2P1 (1001)',
    consent_given: true,
    status: 'PENDING_VALIDATION',
    date_time: '2026-03-15T09:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0002',
    patient_id: 'KLD-2026-0001',
    consultation_type: 'Follow-up',
    weight: 59,
    height: 155,
    bp_systolic: 118,
    bp_diastolic: 76,
    temperature: 36.6,
    bmi: 24.6,
    program_category: 'Maternal',
    chief_complaint: 'Prenatal follow-up, 32 weeks AOG',
    clinical_notes: 'Fundic height 30 cm. FHT 138 bpm. Slight ankle edema.',
    diagnosis: 'Normal pregnancy, G2P1 (1001), mild edema',
    consent_given: true,
    status: 'PENDING_SYNC',
    date_time: '2026-03-25T10:30:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0003',
    patient_id: 'KLD-2026-0002',
    consultation_type: 'New Consultation',
    weight: 82,
    height: 170,
    bp_systolic: 145,
    bp_diastolic: 92,
    temperature: 36.8,
    bmi: 28.4,
    program_category: 'NCD',
    chief_complaint: 'Sumasakit ang ulo, nahihilo',
    clinical_notes: 'Elevated BP on two readings. BMI overweight. Advised lifestyle modification.',
    diagnosis: 'Hypertension Stage 1, Overweight',
    consent_given: true,
    status: 'PENDING_VALIDATION',
    date_time: '2026-03-10T08:15:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0004',
    patient_id: 'KLD-2026-0002',
    consultation_type: 'Follow-up',
    weight: 81,
    height: 170,
    bp_systolic: 138,
    bp_diastolic: 88,
    temperature: 36.7,
    bmi: 28.0,
    program_category: 'NCD',
    chief_complaint: 'Follow-up para sa high blood',
    clinical_notes: 'BP slightly improved. Compliant with medication. Weight down 1 kg.',
    diagnosis: 'Hypertension Stage 1, improving',
    consent_given: true,
    status: 'PENDING_SYNC',
    date_time: '2026-03-24T09:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0005',
    patient_id: 'KLD-2026-0003',
    consultation_type: 'New Consultation',
    weight: 50,
    height: 158,
    bp_systolic: 110,
    bp_diastolic: 70,
    temperature: 37.8,
    bmi: 20.0,
    program_category: 'General',
    chief_complaint: 'Lagnat at ubo, 3 araw na',
    clinical_notes: 'Pharyngeal congestion. No rales. Mild fever.',
    diagnosis: 'Upper respiratory tract infection',
    consent_given: true,
    status: 'PENDING_VALIDATION',
    date_time: '2026-03-18T13:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0006',
    patient_id: 'KLD-2026-0003',
    consultation_type: 'Follow-up',
    weight: 50,
    height: 158,
    bp_systolic: 112,
    bp_diastolic: 72,
    temperature: 36.5,
    bmi: 20.0,
    program_category: 'General',
    chief_complaint: 'Follow-up for URTI, feeling better',
    clinical_notes: 'Afebrile. Cough resolving. Clear lungs.',
    diagnosis: 'URTI, resolving',
    consent_given: true,
    status: 'PENDING_VALIDATION',
    date_time: '2026-03-22T10:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0007',
    patient_id: 'KLD-2026-0004',
    consultation_type: 'New Consultation',
    weight: 65,
    height: 162,
    bp_systolic: 150,
    bp_diastolic: 95,
    temperature: 36.4,
    bmi: 24.8,
    program_category: 'NCD',
    chief_complaint: 'Regular check-up, may diabetes at high blood',
    clinical_notes: 'Known DM type 2 and hypertension. On Metformin and Amlodipine. FBS needed.',
    diagnosis: 'DM type 2, Hypertension Stage 2',
    consent_given: true,
    status: 'PENDING_VALIDATION',
    date_time: '2026-03-12T08:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0008',
    patient_id: 'KLD-2026-0004',
    consultation_type: 'Follow-up',
    weight: 64,
    height: 162,
    bp_systolic: 142,
    bp_diastolic: 90,
    temperature: 36.5,
    bmi: 24.4,
    program_category: 'NCD',
    chief_complaint: 'Follow-up for DM and HPN',
    clinical_notes: 'BP still elevated. Compliant with meds. Refer to RHU for FBS.',
    diagnosis: 'DM type 2, Hypertension Stage 2, for lab work',
    consent_given: true,
    status: 'PENDING_SYNC',
    date_time: '2026-03-26T08:30:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0009',
    patient_id: 'KLD-2026-0005',
    consultation_type: 'New Consultation',
    weight: 48,
    height: 152,
    bp_systolic: 100,
    bp_diastolic: 65,
    temperature: 36.6,
    bmi: 20.8,
    program_category: 'Nutrition',
    chief_complaint: 'Weight monitoring, underweight noon',
    clinical_notes: 'BMI normal range now. Improved appetite. Advised continued balanced diet.',
    diagnosis: 'Nutritional assessment — normal BMI',
    consent_given: true,
    status: 'PENDING_VALIDATION',
    date_time: '2026-03-20T11:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
  {
    id: 'ENC-0010',
    patient_id: 'KLD-2026-0005',
    consultation_type: 'New Consultation',
    weight: 48,
    height: 152,
    bp_systolic: 105,
    bp_diastolic: 68,
    temperature: 37.2,
    bmi: 20.8,
    program_category: 'General',
    chief_complaint: 'Sipon at masakit ang lalamunan',
    clinical_notes: 'Mild rhinorrhea. Erythematous pharynx. No tonsillar exudate.',
    diagnosis: 'Acute pharyngitis',
    consent_given: true,
    status: 'PENDING_SYNC',
    date_time: '2026-03-27T14:00:00Z',
    provider_id: 'bhw-user-001',
    facility_code: 'KLD-BHS-01',
  },
]

export function nextPatientId(): string {
  const n = mockPatients.length + 1
  return `KLD-2026-${String(n).padStart(4, '0')}`
}
